# This is run when starting a Gitpod workspace on this repository

image: leanprovercommunity/gitpod4

vscode:
  extensions:
    - leanprover.lean4 # install the Lean 4 VS Code extension

tasks:
  - init: |
      elan self update
      lake exe cache get
      sudo apt-get update
      sudo apt install ruby ruby-dev -y
      sudo gem install bundler
      cp README.md website/index.md
      python3 scripts/upstreaming_dashboard.py
      cd website
      bundle install
      cd ..
