/-
Copyright (c) 2023 Yaël Dillies, Bhavik Mehta. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yaël Dillies, Bhavik Mehta
-/
import Mathlib.Combinatorics.SimpleGraph.Triangle.Basic

/-!
# Construct a tripartite graph from its triangles

This file contains the construction of a simple graph on `α ⊕ β ⊕ γ` from a list of triangles
`(a, b, c)` (with `a` in the first summand, `b` in the second, `c` in the third).

We call
* `t : finset (α × β × γ)` the set of *triangle indices* (its elements are not triangles within the
  graph but instead index them).
* *explicit* a triangle of the constructed graph coming from a triangle index.
* *accidental* a triangle of the constructed graph not coming from a triangle.

The two important properties of this construction are:
* `simple_graph.tripartite_from_triangles.explicit_disjoint`: Whether the explicit triangles are
  edge-disjoint.
* `simple_graph.tripartite_from_triangles.no_accidental`: Whether all triangles are explicit.

This construction shows up unrelatingly twice in the theory of Roth numbers:
* The lower bound of the Ruzsa-Szemerédi problem: From a Salem-Spencer set `s` on a commutative ring
  `α` (in which `2` is invertible), we build a locally linear graph on `α ⊕ α ⊕ α`. The triangle
  indices are `(x, x + a, x + 2 * a)` for `x` any element and `a ∈ s`. The explicit triangles are
  edge-disjoint and accidental triangles correspond to arithmetic progressions of length 3 in `s`.
* The proof of the corners theorem from the triangle removal lemma. For a subset `s` of the `n × n`
  grid, we construct a tripartite graph whose vertices are the horizontal, vertical and diagonal
  lines in the grid. The explicit triangles are `(h, v, d)` where `h`, `v`, `d` are horizontal,
  vertical, diagonal lines that intersect in an element of `s`. The explicit triangles are
  edge-disjoint. Accidental triangles correspond to non-trivial corners.

# Main declarations

* `simple_graph.tripartite_from_triangles.graph`: The tripartite simple graph generated by the given
  triangle indices.
* `simple_graph.tripartite_from_triangles.explicit_disjoint`: Predicate on triangle indices for the
  constructed graph to have edge-disjoint explicit triangles.
* `simple_graph.tripartite_from_triangles.no_accidental`: Predicate on triangle indices for there to
  be no accidental triangles.
* `simple_graph.tripartite_from_triangles.locally_linear`: If both predicates hold, the constructed
  graph is locally linear.
-/


open Finset Function Sum3

variable {α β γ 𝕜 : Type _} [LinearOrderedField 𝕜] {t : Finset (α × β × γ)} {a a' : α} {b b' : β}
  {c c' : γ} {x : α × β × γ} {ε : 𝕜}

namespace SimpleGraph

namespace TripartiteFromTriangles

/-- The underlying relation of the tripartite-from-triangles graph. Two vertices are related iff
there exists a triangle index containing them both. -/
@[mk_iff]
inductive Rel (t : Finset (α × β × γ)) : Sum α (Sum β γ) → Sum α (Sum β γ) → Prop
  | in₀₁ ⦃a b c⦄ : (a, b, c) ∈ t → Rel (in₀ a) (in₁ b)
  | in₁₀ ⦃a b c⦄ : (a, b, c) ∈ t → Rel (in₁ b) (in₀ a)
  | in₀₂ ⦃a b c⦄ : (a, b, c) ∈ t → Rel (in₀ a) (in₂ c)
  | in₂₀ ⦃a b c⦄ : (a, b, c) ∈ t → Rel (in₂ c) (in₀ a)
  | in₁₂ ⦃a b c⦄ : (a, b, c) ∈ t → Rel (in₁ b) (in₂ c)
  | in₂₁ ⦃a b c⦄ : (a, b, c) ∈ t → Rel (in₂ c) (in₁ b)

open Rel

theorem rel_irrefl : ∀ x, ¬Rel t x x :=
  fun.

theorem rel_symm : Symmetric (Rel t) := fun x y h => by cases h <;> constructor <;> assumption

/-- The tripartite-from-triangles graph. Two vertices are related iff there exists a triangle index
containing them both. -/
def graph (t : Finset (α × β × γ)) : SimpleGraph (Sum α (Sum β γ)) :=
  ⟨Rel t, rel_symm, rel_irrefl⟩

namespace Graph

@[simp]
theorem not_in₀₀ : ¬(graph t).Adj (in₀ a) (in₀ a') :=
  fun.

@[simp]
theorem not_in₁₁ : ¬(graph t).Adj (in₁ b) (in₁ b') :=
  fun.

@[simp]
theorem not_in₂₂ : ¬(graph t).Adj (in₂ c) (in₂ c') :=
  fun.

@[simp]
theorem in₀₁_iff : (graph t).Adj (in₀ a) (in₁ b) ↔ ∃ c, (a, b, c) ∈ t :=
  ⟨by rintro ⟨⟩; exact ⟨_, ‹_›⟩, fun ⟨_, h⟩ => in₀₁ h⟩

@[simp]
theorem in₁₀_iff : (graph t).Adj (in₁ b) (in₀ a) ↔ ∃ c, (a, b, c) ∈ t :=
  ⟨by rintro ⟨⟩; exact ⟨_, ‹_›⟩, fun ⟨_, h⟩ => in₁₀ h⟩

@[simp]
theorem in₀₂_iff : (graph t).Adj (in₀ a) (in₂ c) ↔ ∃ b, (a, b, c) ∈ t :=
  ⟨by rintro ⟨⟩; exact ⟨_, ‹_›⟩, fun ⟨_, h⟩ => in₀₂ h⟩

@[simp]
theorem in₂₀_iff : (graph t).Adj (in₂ c) (in₀ a) ↔ ∃ b, (a, b, c) ∈ t :=
  ⟨by rintro ⟨⟩; exact ⟨_, ‹_›⟩, fun ⟨_, h⟩ => in₂₀ h⟩

@[simp]
theorem in₁₂_iff : (graph t).Adj (in₁ b) (in₂ c) ↔ ∃ a, (a, b, c) ∈ t :=
  ⟨by rintro ⟨⟩; exact ⟨_, ‹_›⟩, fun ⟨_, h⟩ => in₁₂ h⟩

@[simp]
theorem in₂₁_iff : (graph t).Adj (in₂ c) (in₁ b) ↔ ∃ a, (a, b, c) ∈ t :=
  ⟨by rintro ⟨⟩; exact ⟨_, ‹_›⟩, fun ⟨_, h⟩ => in₂₁ h⟩

theorem in₀₁_iff' :
    (graph t).Adj (in₀ a) (in₁ b) ↔ ∃ (x : α × β × γ) (hx : x ∈ t), x.1 = a ∧ x.2.1 = b :=
  ⟨by rintro ⟨⟩; exact ⟨_, ‹_›, rfl, rfl⟩, by rintro ⟨⟨a, b, c⟩, h, rfl, rfl⟩; constructor;
    assumption⟩

theorem in₁₀_iff' :
    (graph t).Adj (in₁ b) (in₀ a) ↔ ∃ (x : α × β × γ) (hx : x ∈ t), x.2.1 = b ∧ x.1 = a :=
  ⟨by rintro ⟨⟩; exact ⟨_, ‹_›, rfl, rfl⟩, by rintro ⟨⟨a, b, c⟩, h, rfl, rfl⟩; constructor;
    assumption⟩

theorem in₀₂_iff' :
    (graph t).Adj (in₀ a) (in₂ c) ↔ ∃ (x : α × β × γ) (hx : x ∈ t), x.1 = a ∧ x.2.2 = c :=
  ⟨by rintro ⟨⟩; exact ⟨_, ‹_›, rfl, rfl⟩, by rintro ⟨⟨a, b, c⟩, h, rfl, rfl⟩; constructor;
    assumption⟩

theorem in₂₀_iff' :
    (graph t).Adj (in₂ c) (in₀ a) ↔ ∃ (x : α × β × γ) (hx : x ∈ t), x.2.2 = c ∧ x.1 = a :=
  ⟨by rintro ⟨⟩; exact ⟨_, ‹_›, rfl, rfl⟩, by rintro ⟨⟨a, b, c⟩, h, rfl, rfl⟩; constructor;
    assumption⟩

theorem in₁₂_iff' :
    (graph t).Adj (in₁ b) (in₂ c) ↔ ∃ (x : α × β × γ) (hx : x ∈ t), x.2.1 = b ∧ x.2.2 = c :=
  ⟨by rintro ⟨⟩; exact ⟨_, ‹_›, rfl, rfl⟩, by rintro ⟨⟨a, b, c⟩, h, rfl, rfl⟩; constructor;
    assumption⟩

theorem in₂₁_iff' :
    (graph t).Adj (in₂ c) (in₁ b) ↔ ∃ (x : α × β × γ) (hx : x ∈ t), x.2.2 = c ∧ x.2.1 = b :=
  ⟨by rintro ⟨⟩; exact ⟨_, ‹_›, rfl, rfl⟩, by rintro ⟨⟨a, b, c⟩, h, rfl, rfl⟩; constructor;
    assumption⟩

end Graph

open Graph

/-- Predicate on the triangle indices for the explicit triangles to be edge-disjoint. -/
class ExplicitDisjoint (t : Finset (α × β × γ)) : Prop where
  inj₀ : ∀ ⦃a b c a'⦄, (a, b, c) ∈ t → (a', b, c) ∈ t → a = a'
  inj₁ : ∀ ⦃a b c b'⦄, (a, b, c) ∈ t → (a, b', c) ∈ t → b = b'
  inj₂ : ∀ ⦃a b c c'⦄, (a, b, c) ∈ t → (a, b, c') ∈ t → c = c'

/-- Predicate on the triangle indices for there to be no accidental triangle.

Note that we cheat a bit, since the exact translation of this informal description would have
`(a', b', c') ∈ s` as a conclusion rather than `a = a' ∨ b = b' ∨ c = c'`. Those conditions are
equivalent when the explicit triangles are edge-disjoint (which is the case we care about). -/
class NoAccidental (t : Finset (α × β × γ)) : Prop where
  wow :
    ∀ ⦃a a' b b' c c'⦄, (a', b, c) ∈ t → (a, b', c) ∈ t → (a, b, c') ∈ t → a = a' ∨ b = b' ∨ c = c'

section DecidableEq

variable [DecidableEq α] [DecidableEq β] [DecidableEq γ]

instance : DecidableRel (graph t).Adj
  | in₀ a, in₀ a' => Decidable.isFalse not_in₀₀
  | in₀ a, in₁ b' => decidable_of_iff' _ in₀₁_iff'
  | in₀ a, in₂ c' => decidable_of_iff' _ in₀₂_iff'
  | in₁ b, in₀ a' => decidable_of_iff' _ in₁₀_iff'
  | in₁ b, in₁ b' => Decidable.isFalse not_in₁₁
  | in₁ b, in₂ b' => decidable_of_iff' _ in₁₂_iff'
  | in₂ c, in₀ a' => decidable_of_iff' _ in₂₀_iff'
  | in₂ c, in₁ b' => decidable_of_iff' _ in₂₁_iff'
  | in₂ c, in₂ b' => Decidable.isFalse not_in₂₂

/-- This lemma reorders the elements of a triangle in the tripartite graph. It turns a triangle
`{x, y, z}` into a triangle `{a, b, c}` where `a : α `, `b : β`, `c : γ`. -/
theorem graph_triple ⦃x y z⦄ :
    (graph t).Adj x y →
      (graph t).Adj x z →
        (graph t).Adj y z →
          ∃ a b c,
            ({in₀ a, in₁ b, in₂ c} : Finset (Sum α (Sum β γ))) = {x, y, z} ∧
              (graph t).Adj (in₀ a) (in₁ b) ∧
                (graph t).Adj (in₀ a) (in₂ c) ∧ (graph t).Adj (in₁ b) (in₂ c) := by
  rintro (_ | _ | _) (_ | _ | _) (_ | _ | _) <;>
        refine'
          ⟨_, _, _, by ext <;> simp only [Finset.mem_insert, Finset.mem_singleton] <;> try tauto, _,
            _, _⟩ <;>
      constructor <;>
    assumption

/-- The map that turns a triangle index into an explicit triangle. -/
@[simps]
def toTriangle : α × β × γ ↪ Finset (Sum α (Sum β γ))
    where
  toFun x := {in₀ x.1, in₁ x.2.1, in₂ x.2.2}
  inj' := fun ⟨a, b, c⟩ ⟨a', b', c'⟩ => by
    simpa only [Finset.Subset.antisymm_iff, Finset.subset_iff, mem_insert, mem_singleton,
      forall_eq_or_imp, forall_eq, Prod.mk.inj_iff, or_false_iff, false_or_iff, in₀, in₁, in₂,
      Sum.inl.inj_eq, Sum.inr.inj_eq] using And.left

theorem toTriangle_is_3_clique (hx : x ∈ t) : (graph t).IsNClique 3 (toTriangle x) := by
  rcases x with ⟨a, b, c⟩
  simp only [to_triangle_apply, is_3_clique_triple_iff, in₀₁_iff, in₀₂_iff, in₁₂_iff]
  exact ⟨⟨_, hx⟩, ⟨_, hx⟩, _, hx⟩

theorem exists_mem_toTriangle {x y : Sum α (Sum β γ)} (hxy : (graph t).Adj x y) :
    ∃ z ∈ t, x ∈ toTriangle z ∧ y ∈ toTriangle z := by cases hxy <;> exact ⟨_, ‹_›, by simp⟩

theorem is_3_clique_iff [NoAccidental t] {s : Finset (Sum α (Sum β γ))} :
    (graph t).IsNClique 3 s ↔ ∃ x, x ∈ t ∧ toTriangle x = s := by
  refine' ⟨fun h => _, _⟩
  · rw [is_3_clique_iff] at h
    obtain ⟨x, y, z, hxy, hxz, hyz, rfl⟩ := h
    obtain ⟨a, b, c, habc, hab, hac, hbc⟩ := graph_triple hxy hxz hyz
    refine' ⟨(a, b, c), _, habc⟩
    obtain ⟨c', hc'⟩ := in₀₁_iff.1 hab
    obtain ⟨b', hb'⟩ := in₀₂_iff.1 hac
    obtain ⟨a', ha'⟩ := in₁₂_iff.1 hbc
    obtain rfl | rfl | rfl := no_accidental.wow ha' hb' hc' <;> assumption
  · rintro ⟨x, hx, rfl⟩
    exact to_triangle_is_3_clique hx

theorem toTriangle_surjOn [NoAccidental t] :
    (t : Set (α × β × γ)).SurjOn toTriangle ((graph t).cliqueSet 3) := fun s => is_3_clique_iff.1

variable (t)

theorem map_toTriangle_disjoint [ExplicitDisjoint t] :
    (t.map toTriangle : Set (Finset (Sum α (Sum β γ)))).Pairwise fun x y =>
      (x ∩ y : Set (Sum α (Sum β γ))).Subsingleton := by
  intro
  simp only [Finset.coe_map, Set.mem_image, Finset.mem_coe, Prod.exists, Ne.def,
    forall_exists_index, and_imp]
  rintro a b c habc rfl e x y z hxyz rfl h'
  have := ne_of_apply_ne _ h'
  simp only [Ne.def, Prod.mk.inj_iff, not_and] at this
  simp only [to_triangle_apply, in₀, in₁, in₂, Set.mem_inter_iff, mem_insert, mem_singleton,
    mem_coe, and_imp, Sum.forall, or_false_iff, forall_eq, false_or_iff, eq_self_iff_true,
    imp_true_iff, true_and_iff, and_true_iff, Set.Subsingleton]
  suffices ¬(a = x ∧ b = y) ∧ ¬(a = x ∧ c = z) ∧ ¬(b = y ∧ c = z) by tauto
  refine' ⟨_, _, _⟩
  · rintro ⟨rfl, rfl⟩
    exact this rfl rfl (explicit_disjoint.inj₂ habc hxyz)
  · rintro ⟨rfl, rfl⟩
    exact this rfl (explicit_disjoint.inj₁ habc hxyz) rfl
  · rintro ⟨rfl, rfl⟩
    exact this (explicit_disjoint.inj₀ habc hxyz) rfl rfl

theorem cliqueSet_eq_image [NoAccidental t] : (graph t).cliqueSet 3 = toTriangle '' t := by
  ext <;> exact is_3_clique_iff

section Fintype

variable [Fintype α] [Fintype β] [Fintype γ]

theorem cliqueFinset_eq_image [NoAccidental t] : (graph t).cliqueFinset 3 = t.image toTriangle :=
  coe_injective <| by push_cast; exact clique_set_eq_image _

theorem cliqueFinset_eq_map [NoAccidental t] : (graph t).cliqueFinset 3 = t.map toTriangle := by
  simp [clique_finset_eq_image, map_eq_image]

@[simp]
theorem card_triangles [NoAccidental t] : ((graph t).cliqueFinset 3).card = t.card := by
  rw [clique_finset_eq_map, card_map]

theorem farFromTriangleFree [ExplicitDisjoint t] {ε : 𝕜}
    (ht : ε * ((Fintype.card α + Fintype.card β + Fintype.card γ) ^ 2 : ℕ) ≤ t.card) :
    (graph t).FarFromTriangleFree ε :=
  farFromTriangleFree_of_disjoint_triangles (t.map toTriangle)
      (map_subset_iff_subset_preimage.2 fun x hx => by simpa using to_triangle_is_3_clique hx)
      (map_toTriangle_disjoint t) <|
    by simpa [add_assoc] using ht

end Fintype

end DecidableEq

variable (t)

theorem locallyLinear [ExplicitDisjoint t] [NoAccidental t] : (graph t).LocallyLinear := by
  classical
  refine' ⟨_, fun x y hxy => _⟩
  · unfold edge_disjoint_triangles
    convert map_to_triangle_disjoint t
    rw [clique_set_eq_image, coe_map]
  · obtain ⟨z, hz, hxy⟩ := exists_mem_to_triangle hxy
    exact ⟨_, to_triangle_is_3_clique hz, hxy⟩

end TripartiteFromTriangles

end SimpleGraph
