on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_project:
    runs-on: ubuntu-latest
    name: Build project
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: checkout project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: print files to upstream
        run: |
          grep -r --exclude-dir=ExampleSheets --files-without-match 'import LeanCamCombi' LeanCamCombi | sort > 1.txt
          grep -r --exclude-dir=ExampleSheets --files-with-match 'sorry' LeanCamCombi | sort > 2.txt
          comm -23 1.txt 2.txt | sed -e 's/^\(.*\)$/- [`\1`](https:\/\/github.com\/YaelDillies\/LeanCamCombi\/blob\/main\/\1)/' > docs/_includes/files_to_upstream.md
          rm 1.txt 2.txt

      - name: install elan
        run: curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y --default-toolchain leanprover/lean4:4.0.0

      - name: get cache
        run: ~/.elan/bin/lake -Kenv=dev exe cache get

      - name: build project
        run: ~/.elan/bin/lake -Kenv=dev build LeanCamCombi

      - name: build documentation
        run: ~/.elan/bin/lake -Kenv=dev build LeanCamCombi:docs

      - name: copy documentation
        run: cp -R build/doc docs/

      - name: remove .gitignore for gh-pages
        run: rm docs/.gitignore

      - name: Bundle dependencies
        uses: ruby/setup-ruby@v1
        with:
          working-directory: docs
          ruby-version: "3.0" # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: bundle website
        working-directory: docs
        run: JEKYLL_ENV=production bundle exec jekyll build

      - name: upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'docs/_site'

      - name: deploy website
        uses: actions/deploy-pages@v1
