on:
  push:
    branches-ignore:
      - master

jobs:
  style_lint:
    name: Lint style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Don't 'import Mathlib', use precise imports
        if: always()
        run: |
          ! (find Toric -name "*.lean" -type f -print0 | xargs -0 grep -E -n '^import Mathlib$')

      - name: Files in Toric.Mathlib can't import Toric files outside Toric.Mathlib
        run: |
          ! (find Toric/Mathlib -name "*.lean" -type f -print0 | xargs -0 grep -E -n '^import Toric.(?!Mathlib)')

  build_project:
    runs-on: ubuntu-latest
    name: Build project
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install elan
        run: curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y --default-toolchain leanprover/lean4:4.18.0

      - name: Get cache
        run: ~/.elan/bin/lake exe cache get || true

      - name: Build project
        run: ~/.elan/bin/lake build Toric

      # - name: Cache documentation
      #   uses: actions/cache@v4
      #   with:
      #     path: website/docs
      #     key: MathlibDoc-${{ hashFiles('lake-manifest.json') }}
      #     restore-keys: MathlibDoc-

      # - name: Build documentation
      #   run: scripts/build_docs.sh

      # - name: Build blueprint
      #   uses: xu-cheng/texlive-action@v2
      #   with:
      #     docker_image: ghcr.io/xu-cheng/texlive-full:20231201
      #     run: |
      #       # Install necessary dependencies and build the blueprint
      #       apk update
      #       apk add --update make py3-pip git pkgconfig graphviz graphviz-dev gcc musl-dev
      #       git config --global --add safe.directory $GITHUB_WORKSPACE
      #       git config --global --add safe.directory `pwd`
      #       python3 -m venv env
      #       source env/bin/activate
      #       pip install --upgrade pip requests wheel
      #       pip install pygraphviz --global-option=build_ext --global-option="-L/usr/lib/graphviz/" --global-option="-R/usr/lib/graphviz/"
      #       pip install leanblueprint
      #       leanblueprint pdf
      #       leanblueprint web
